name: iosApp
options:
  bundleIdPrefix: io.github.devmugi.arcane.catalog
  deploymentTarget:
    iOS: "15.0"
  xcodeVersion: "15.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS
    sources:
      - path: iosApp
        excludes:
          - "*.xcassets/AppIcon.appiconset/*.png"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.devmugi.arcane.catalog.iosApp
        INFOPLIST_FILE: iosApp/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(SRCROOT)/../composeApp/build/bin/iosSimulatorArm64/debugFramework"
          - "$(SRCROOT)/../composeApp/build/bin/iosArm64/releaseFramework"
        OTHER_LDFLAGS:
          - "$(inherited)"
          - "-framework"
          - "ComposeApp"
        ENABLE_USER_SCRIPT_SANDBOXING: NO
    preBuildScripts:
      - name: "Build Kotlin Framework"
        script: |
          cd "$SRCROOT/../.."
          ./gradlew :catalog:composeApp:iosSimulatorArm64MainBinaries
        basedOnDependencyAnalysis: false
    dependencies: []
